"""Tool package exports for TCMAgent."""

from .case_tools import (
    CASE_STORE,
    AppendCaseEvidenceInput,
    AppendCaseEvidenceOutput,
    CaseNotFoundError,
    CaseRecord,
    CaseStageLockedError,
    CaseToolError,
    CreateCaseInput,
    CreateCaseOutput,
    GetCaseStateInput,
    GetCaseStateOutput,
    InMemoryCaseStore,
    InvalidCaseTransitionError,
    LockCaseStageInput,
    LockCaseStageOutput,
    PatientProfileInput,
    RecordQuestionAskedInput,
    RecordQuestionAskedOutput,
    SaveCaseSummaryInput,
    SaveCaseSummaryOutput,
    SaveRiskDecisionInput,
    SaveRiskDecisionOutput,
    SetCaseStageInput,
    SetCaseStageOutput,
    UpdateCaseFactsInput,
    UpdateCaseFactsOutput,
    append_case_evidence,
    create_case,
    enrich_patient_profile,
    get_case_state,
    lock_case_stage,
    record_question_asked,
    save_case_summary,
    save_risk_decision,
    set_case_stage,
    update_case_candidates,
    update_case_facts,
)
from .case_tools import (
    ToolMetadata as CaseToolMetadata,
)
from .graph_tools import (
    BuildEvidencePathInput,
    BuildEvidencePathOutput,
    CandidateContextInput,
    ExplainQuestionRationaleInput,
    ExplainQuestionRationaleOutput,
    FindDiscriminativeQuestionsInput,
    FindDiscriminativeQuestionsOutput,
    QueryGraphCandidatesInput,
    QueryGraphCandidatesOutput,
    RankCandidateHypothesesInput,
    RankCandidateHypothesesOutput,
    UpdateGraphEvidenceProjectionInput,
    UpdateGraphEvidenceProjectionOutput,
    build_evidence_path,
    explain_question_rationale,
    find_discriminative_questions,
    query_graph_candidates,
    rank_candidate_hypotheses,
    update_graph_evidence_projection,
)
from .graph_tools import (
    ToolMetadata as GraphToolMetadata,
)
from .safety_tools import (
    CheckContraindicationsInput,
    CheckContraindicationsOutput,
    CheckSpecialPopulationRisksInput,
    CheckSpecialPopulationRisksOutput,
    IssueRiskDecisionInput,
    IssueRiskDecisionOutput,
    SafetyToolError,
    ScreenRedFlagsInput,
    ScreenRedFlagsOutput,
    check_contraindications,
    check_special_population_risks,
    issue_risk_decision,
    run_full_safety_check,
    screen_red_flags,
)
from .safety_tools import (
    ToolMetadata as SafetyToolMetadata,
)
from .summary_tools import (
    CaseTraceOutput,
    ClinicianSummaryOutput,
    ExportCaseTraceInput,
    GenerateClinicianSummaryInput,
    GeneratePatientSummaryInput,
    PatientSummaryTemplateOutput,
    RedFlagSummaryItem,
    SummaryToolError,
    export_case_trace,
    generate_clinician_summary,
    generate_patient_summary_template,
)
from .summary_tools import (
    ToolMetadata as SummaryToolMetadata,
)
from .triage_tools import (
    ClassifyVisitRouteInput,
    ClassifyVisitRouteOutput,
    RunTriageInput,
    TagSpecialPopulationInput,
    TagSpecialPopulationOutput,
    TriageOutput,
    TriageToolError,
    classify_visit_route,
    run_triage,
    tag_special_population,
)
from .triage_tools import (
    ToolMetadata as TriageToolMetadata,
)

__all__ = [
    # ── constants ──────────────────────────────────────────────────────
    "CASE_STORE",
    # ── classes (A-Z) ──────────────────────────────────────────────────
    "AppendCaseEvidenceInput",
    "AppendCaseEvidenceOutput",
    "BuildEvidencePathInput",
    "BuildEvidencePathOutput",
    "CandidateContextInput",
    "CaseNotFoundError",
    "CaseRecord",
    "CaseStageLockedError",
    "CaseToolError",
    "CaseToolMetadata",
    "CaseTraceOutput",
    "CheckContraindicationsInput",
    "CheckContraindicationsOutput",
    "CheckSpecialPopulationRisksInput",
    "CheckSpecialPopulationRisksOutput",
    "ClassifyVisitRouteInput",
    "ClassifyVisitRouteOutput",
    "ClinicianSummaryOutput",
    "CreateCaseInput",
    "CreateCaseOutput",
    "ExplainQuestionRationaleInput",
    "ExplainQuestionRationaleOutput",
    "ExportCaseTraceInput",
    "FindDiscriminativeQuestionsInput",
    "FindDiscriminativeQuestionsOutput",
    "GenerateClinicianSummaryInput",
    "GeneratePatientSummaryInput",
    "GetCaseStateInput",
    "GetCaseStateOutput",
    "GraphToolMetadata",
    "InMemoryCaseStore",
    "InvalidCaseTransitionError",
    "IssueRiskDecisionInput",
    "IssueRiskDecisionOutput",
    "LockCaseStageInput",
    "LockCaseStageOutput",
    "PatientProfileInput",
    "PatientSummaryTemplateOutput",
    "QueryGraphCandidatesInput",
    "QueryGraphCandidatesOutput",
    "RankCandidateHypothesesInput",
    "RankCandidateHypothesesOutput",
    "RecordQuestionAskedInput",
    "RecordQuestionAskedOutput",
    "RedFlagSummaryItem",
    "RunTriageInput",
    "SafetyToolError",
    "SafetyToolMetadata",
    "SaveCaseSummaryInput",
    "SaveCaseSummaryOutput",
    "SaveRiskDecisionInput",
    "SaveRiskDecisionOutput",
    "ScreenRedFlagsInput",
    "ScreenRedFlagsOutput",
    "SetCaseStageInput",
    "SetCaseStageOutput",
    "SummaryToolError",
    "SummaryToolMetadata",
    "TagSpecialPopulationInput",
    "TagSpecialPopulationOutput",
    "TriageOutput",
    "TriageToolError",
    "TriageToolMetadata",
    "UpdateCaseFactsInput",
    "UpdateCaseFactsOutput",
    "UpdateGraphEvidenceProjectionInput",
    "UpdateGraphEvidenceProjectionOutput",
    # ── functions (a-z) ────────────────────────────────────────────────
    "append_case_evidence",
    "build_evidence_path",
    "check_contraindications",
    "check_special_population_risks",
    "classify_visit_route",
    "create_case",
    "enrich_patient_profile",
    "explain_question_rationale",
    "export_case_trace",
    "find_discriminative_questions",
    "generate_clinician_summary",
    "generate_patient_summary_template",
    "get_case_state",
    "issue_risk_decision",
    "lock_case_stage",
    "query_graph_candidates",
    "rank_candidate_hypotheses",
    "record_question_asked",
    "run_full_safety_check",
    "run_triage",
    "save_case_summary",
    "save_risk_decision",
    "screen_red_flags",
    "set_case_stage",
    "tag_special_population",
    "update_case_candidates",
    "update_case_facts",
    "update_graph_evidence_projection",
]
